### ISSUE TITLE
JCenter shutdown: Publish to Maven Central

### ISSUE THREAD

**Issue by joschi** [brightsparklabs/dropwizard-external-auth-bundle#9]
With the permanent shutdown of JCenter (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) the `dropwizard-external-auth-bundle` artifacts aren't available anymore.

It would be great if you could publish the project to Maven Central or another public Maven repository.

**Comment by al-jeyapal** [comment]
Resolved by #10 
Should appear shortly at: https://central.sonatype.com/namespace/com.brightsparklabs
